version: '3.7'

services:
  web:
    build: .
    command: gunicorn exif.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./exif/:/usr/src/exif/
      - ./exif/media/:/usr/src/exif/media
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./exif/media/:/usr/src/exif/media
